export const assignmentTabs = [
  { id: 'dashboard', label: 'Dashboard' },
  { id: 'list', label: 'Danh sách bài tập' },
  { id: 'create', label: 'Tạo bài tập' },
  { id: 'stats', label: 'Thống kê' },
]

export const assignmentFilters = {
  skills: ['Tất cả kỹ năng', 'Grammar', 'Vocabulary', 'Reading', 'Listening', 'Writing', 'Speaking'],
  levels: ['Tất cả trình độ', 'Starter', 'Mover', 'Flyer', 'A1', 'A2', 'B1', 'B2', 'IELTS', 'TOEIC'],
  types: ['Tất cả loại bài', 'Quiz', 'Homework', 'Practice', 'Exam', 'Project'],
  creators: ['Tất cả người tạo', 'Ms. Linh', 'Mr. Nam', 'Ms. Hạnh', 'Teacher Admin'],
}

export const allowedAssignmentFiles = ['PDF', 'Word', 'PowerPoint', 'Excel', 'Audio', 'Video', 'ZIP']

export const assignmentBank = [
  {
    id: 'ASG-001',
    title: 'Quiz Vocabulary - Unit 4',
    description: 'Ôn tập từ vựng Unit 4 cho lớp IELTS Foundation.',
    type: 'Quiz',
    skill: 'Vocabulary',
    level: 'IELTS',
    file: 'unit-4-vocabulary.pdf',
    creator: 'Ms. Linh',
    createdAt: '06/08/2026',
    duration: 15,
    maxScore: 10,
    status: 'Đang hoạt động',
  },
  {
    id: 'ASG-002',
    title: 'Present Perfect Grammar Drill',
    description: 'Bài luyện tập thì hiện tại hoàn thành.',
    type: 'Practice',
    skill: 'Grammar',
    level: 'B1',
    file: 'present-perfect.docx',
    creator: 'Mr. Nam',
    createdAt: '05/08/2026',
    duration: 20,
    maxScore: 10,
    status: 'Mới',
  },
  {
    id: 'ASG-003',
    title: 'Reading Short Passage Practice',
    description: 'Đọc hiểu đoạn văn ngắn theo chủ đề đời sống.',
    type: 'Homework',
    skill: 'Reading',
    level: 'A2',
    file: 'reading-passage.pdf',
    creator: 'Ms. Hạnh',
    createdAt: '03/08/2026',
    duration: 25,
    maxScore: 10,
    status: 'Đã giao',
  },
  {
    id: 'ASG-004',
    title: 'Listening Part 2 Drill',
    description: 'Luyện nghe TOEIC Part 2 với audio ngắn.',
    type: 'Practice',
    skill: 'Listening',
    level: 'TOEIC',
    file: 'toeic-listening-part-2.mp3',
    creator: 'Teacher Admin',
    createdAt: '01/08/2026',
    duration: 18,
    maxScore: 10,
    status: 'Đã giao',
  },
  {
    id: 'ASG-005',
    title: 'Writing Task 1 - Line Graph',
    description: 'Viết mô tả biểu đồ đường IELTS Writing Task 1.',
    type: 'Homework',
    skill: 'Writing',
    level: 'IELTS',
    file: 'writing-line-graph.pptx',
    creator: 'Ms. Linh',
    createdAt: '28/07/2026',
    duration: 35,
    maxScore: 10,
    status: 'Hết hạn',
  },
  {
    id: 'ASG-006',
    title: 'Speaking Club - Opinion Cards',
    description: 'Bộ thẻ luyện nói nêu quan điểm.',
    type: 'Project',
    skill: 'Speaking',
    level: 'B2',
    file: 'opinion-cards.zip',
    creator: 'Mr. Nam',
    createdAt: '25/07/2026',
    duration: 12,
    maxScore: 10,
    status: 'Đang hoạt động',
  },
]

export const assignableClasses = [
  { id: 'IELTS-01', name: 'IELTS 01', students: ['Nguyễn Văn A', 'Nguyễn Văn B', 'Trần Minh Anh', 'Lê Gia Hân'] },
  { id: 'IELTS-02', name: 'IELTS 02', students: ['Phạm Minh Khang', 'Vũ Bảo Ngọc', 'Bùi Khánh Vy', 'Đặng Minh Quân'] },
  { id: 'KIDS-03', name: 'Kids 03', students: ['Đỗ An Nhiên', 'Mai Đức Long', 'Ngô Khánh Linh', 'Hoàng Tú Anh'] },
]
