const defaultAvatars = [
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80',
  'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=120&q=80',
]

const makeStudents = (prefix, names) =>
  names.map((name, index) => ({
    id: `${prefix}-${index + 1}`,
    avatar: defaultAvatars[index % defaultAvatars.length],
    name,
    attendanceRate: `${96 - index * 4}%`,
    averageScore: Number((8.6 - index * 0.4).toFixed(1)),
    progress: 82 - index * 7,
    homework: `${15 - index}/16`,
    attendanceStatus: ['Có mặt', 'Muộn', 'Nghỉ phép'][index % 3],
  }))

const makeHomework = (title, due, submitted, status = 'Đang giao') => [
  { title, due, submitted, status },
]

export const myClasses = [
  {
    id: 'IELTS-F01',
    name: 'IELTS Foundation 01',
    teacher: 'Cô Linh Trần',
    room: 'Phòng 301',
    time: 'Thứ 2, Thứ 4 - 08:00',
    size: 18,
    progress: 68,
    level: 'IELTS 4.0-5.0',
    status: 'Đang học',
    nextLesson: 'Unit 6 - Describing trends',
    students: makeStudents('IELTS-F01', ['Nguyễn Minh Anh', 'Trần Bảo Lâm', 'Lê Gia Hân']),
    homework: [
      { title: 'Writing Task 1 - Line Graph', due: '08/08/2026', submitted: '14/18', status: 'Cần chấm' },
      { title: 'Vocabulary Unit 6 Practice', due: '06/08/2026', submitted: '18/18', status: 'Đã nộp đủ' },
    ],
  },
  {
    id: 'KIDS-E01',
    name: 'Elementary Kids',
    teacher: 'Cô Linh Trần',
    room: 'Phòng 104',
    time: 'Thứ 3, Thứ 5 - 14:00',
    size: 16,
    progress: 42,
    level: 'Elementary',
    status: 'Đang học',
    nextLesson: 'Phonics review & speaking game',
    students: makeStudents('KIDS-E01', ['Đỗ An Nhiên', 'Phạm Minh Khang', 'Vũ Bảo Ngọc']),
    homework: makeHomework('Short Vowels Worksheet', '09/08/2026', '12/16'),
  },
  {
    id: 'SPK-CLUB',
    name: 'Speaking Club',
    teacher: 'Thầy Minh Phạm',
    room: 'Studio 2',
    time: 'Thứ 6 - 18:30',
    size: 14,
    progress: 54,
    level: 'Communication',
    status: 'Đang học',
    nextLesson: 'Debate: Education and Technology',
    students: makeStudents('SPK-CLUB', ['Hoàng Tú Anh', 'Mai Đức Long', 'Ngô Khánh Linh']),
    homework: makeHomework('Prepare 2-minute opinion speech', '11/08/2026', '9/14'),
  },
  {
    id: 'TOEIC-550',
    name: 'TOEIC 550',
    teacher: 'Cô Linh Trần',
    room: 'Online',
    time: 'Thứ 5, Thứ 7 - 18:00',
    size: 22,
    progress: 76,
    level: 'TOEIC 550+',
    status: 'Đang học',
    nextLesson: 'Part 5 grammar clinic',
    students: makeStudents('TOEIC-550', ['Nguyễn Quốc Huy', 'Bùi Khánh Vy', 'Đặng Minh Quân']),
    homework: makeHomework('TOEIC Part 5 Set 03', '07/08/2026', '20/22', 'Cần chấm'),
  },
  {
    id: 'IELTS-W02',
    name: 'IELTS Writing Boost',
    teacher: 'Cô Linh Trần',
    room: 'Phòng 302',
    time: 'Thứ 3, Thứ 6 - 19:00',
    size: 15,
    progress: 35,
    level: 'IELTS 5.5-6.5',
    status: 'Đang học',
    nextLesson: 'Task 2 - Opinion Essay',
    students: makeStudents('IELTS-W02', ['Phan Hà My', 'Lý Hoàng Nam', 'Đinh Phương Thảo']),
    homework: makeHomework('Opinion Essay Outline', '13/08/2026', '10/15'),
  },
  {
    id: 'KIDS-PHN',
    name: 'Kids Phonics Fun',
    teacher: 'Cô Mai Anh',
    room: 'Phòng 105',
    time: 'Thứ 7 - 09:00',
    size: 12,
    progress: 58,
    level: 'Young Learners',
    status: 'Đang học',
    nextLesson: 'Long vowels and word families',
    students: makeStudents('KIDS-PHN', ['Lâm Bảo Châu', 'Trịnh Gia Bảo', 'Nguyễn Tuệ An']),
    homework: makeHomework('Long Vowels Coloring Sheet', '14/08/2026', '8/12'),
  },
  {
    id: 'COMM-A2',
    name: 'Communication A2',
    teacher: 'Thầy Minh Phạm',
    room: 'Studio 1',
    time: 'Thứ 2, Thứ 5 - 17:30',
    size: 20,
    progress: 47,
    level: 'A2',
    status: 'Đang học',
    nextLesson: 'Ordering food and daily conversations',
    students: makeStudents('COMM-A2', ['Tạ Minh Châu', 'Võ Hoài Nam', 'Đỗ Thanh Vân']),
    homework: makeHomework('Daily Conversation Recording', '15/08/2026', '13/20'),
  },
  {
    id: 'TOEIC-LR',
    name: 'TOEIC Listening Reading',
    teacher: 'Cô Linh Trần',
    room: 'Online',
    time: 'Thứ 4, Chủ nhật - 20:00',
    size: 24,
    progress: 63,
    level: 'TOEIC 650+',
    status: 'Đang học',
    nextLesson: 'Part 3 - Conversations',
    students: makeStudents('TOEIC-LR', ['Nguyễn Hải Đăng', 'Lê Thu Trang', 'Phạm Quốc Bảo']),
    homework: makeHomework('Part 3 Conversation Drill', '16/08/2026', '18/24', 'Cần chấm'),
  },
  {
    id: 'GRAM-B1',
    name: 'Grammar Master B1',
    teacher: 'Cô Mai Anh',
    room: 'Phòng 203',
    time: 'Thứ 3 - 18:00',
    size: 17,
    progress: 81,
    level: 'B1',
    status: 'Đang học',
    nextLesson: 'Relative clauses and connectors',
    students: makeStudents('GRAM-B1', ['Hồ Ngọc Mai', 'Trần Đức Anh', 'Vũ Thanh Tâm']),
    homework: makeHomework('Relative Clauses Practice', '12/08/2026', '16/17', 'Cần chấm'),
  },
]
